cf_car_homepage:
    path:     /
    defaults: { _controller: CFCarBundle:Default:index }

cf_car_travel:
    path:     /travel
    defaults: { _controller: CFCarBundle:Travel:index }

cf_car_competition:
    path:    /competition
    defaults: { _controller: CFCarsBundle:Competition:index }

cf_car_login:
    path:    /login
    defaults: { _controller: CFCarsBundle:Security:login }

