<?php

namespace CF\CarBundle\Repository;

/**
 * AdviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdviceRepository extends \Doctrine\ORM\EntityRepository
{
}
