<?php

namespace CF\CarBundle\Repository;

/**
 * Info_BanqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Info_BanqRepository extends \Doctrine\ORM\EntityRepository
{
}
