<?php

namespace CF\CarBundle\Repository;

/**
 * SponsorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SponsorsRepository extends \Doctrine\ORM\EntityRepository
{
}
