<?php

namespace CF\CarBundle\Repository;

/**
 * TravelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravelRepository extends \Doctrine\ORM\EntityRepository
{
    public function AllTravelByPrefAndDriver(){

        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT ,  FROM CFCarBundle:Travel t
            JOIN p.category c
            WHERE p.id = :id'
    }
}
