<?php

namespace CF\CarBundle\Repository;

/**
 * TravelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravelRepository extends \Doctrine\ORM\EntityRepository
{
    public function AllTravelByPrefAndDriver(){

        $qb=$this->createQueryBuilder('t')
            ->join('t.driverId','driver')
            ->leftJoin('driver.preferencesId','p')
            ->join('driver.UserId','user')
            ->addSelect('driver')
            ->addSelect('p')
            ->addSelect('user');

        return $qb->getQuery()->getResult();
    }
}
